version: '3'
services:
  mysql:
    image: mysql:8.0.41
    container_name: juizodivinodb_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Xaqq123!
      MYSQL_DATABASE: juizodivinodb
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init/backup.sql:/docker-entrypoint-initdb.d/backup.sql
