name: Deploy to DigitalOcean App Platform

on:
  push:
    branches:
      - main 

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy
      run: |
        ssh -o StrictHostKeyChecking=no root@191.252.223.15 "
        source ~/.bashrc &&
        cd juizodivinorpg &&
        git pull origin main &&
        pm2 restart 0
        "
